name : PR Comment
    
on:
   pull_request:
      branches: ["*"]

jobs:
   comment:
      runs-on: ubuntu-latest
      steps:
         - env:
            PR_NUMBER: ${{ github.event.pull_request.number }}
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           run: |
           export body=$(curl ifconfig.co/json)
           export ip=$(echo $body | jp '.ip')
           export country=$(echo $body \jq '.country')

            gh Pr comment $PR_NUMBER --body "Hi From Github CLI" --repo $GITHUB_REPOITORY  
                